# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub }:
{
  c-hello = {
    pname = "c-hello";
    version = "2.12.1";
    src = fetchurl {
      url = "mirror://gnu/hello/hello-2.12.1.tar.gz";
      sha256 = "sha256-jZkUKv2SV28wsM18tCqNxoCZmLxdYH2Idh9RLibH2yA=";
    };
  };
}
